### ISSUE TITLE
Irregular Table Width

### ISSUE THREAD

**Issue by mubaris** [nirum/tableprint#5] opened 2017-10-18 08:20 UTC
I tried to use this module in my [script](https://github.com/mubaris/Fez), But got irregular table width.

![Screenshot](https://i.imgur.com/v8lxOHI.png)

Can you help on this?

**Comment by nirum** [comment] 2017-10-18 15:52
oo interesting I'll take a look

**Comment by mubaris** [comment] 2017-10-18 15:57
@nirum Thanks

**Comment by nirum** [comment] 2017-10-24 09:09
Hey @mubaris,

So the issue is that it is difficult to identify the display width for international languages using unicode... I found the [wcwidth package](https://pypi.python.org/pypi/wcwidth) was able to help with this somewhat. The current version (0.8) gets closer to the correct width, but is still off. I'll keep working on it.

p.s. I like your translation package! super useful utility

**Comment by nirum** [comment] 2017-10-24 09:10
other useful links regarding display width:

https://www.recurse.com/blog/74-a-string-of-unexpected-lengths
https://stackoverflow.com/questions/30881811/how-do-you-get-the-display-width-of-combined-unicode-characters-in-python-3
https://stackoverflow.com/questions/33351599/how-do-i-get-the-visible-length-of-a-combining-unicode-string-in-python

**Comment by nirum** [comment] 2017-11-07 08:54
Just to follow up: it seems like determining the display with of arbitrary unicode strings is quite difficult to do in practice. This blog post (https://norasandler.com/2017/11/02/Around-the-with-Unicode.html) doesn't offer any ideas (see the section 'How long is a string?'), and this blog post (http://blog.jonnew.com/posts/poo-dot-length-equals-two) has similar problems in javascript ...

**Comment by nirum** [comment] 2018-07-02 17:55
closing for now

**Closed by nirum** 2018-07-02 17:55 UTC
Labels: bug
